# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

newline_style = "Unix"

# nightly

ignore = [
    "frontend/src/generated",
]
normalize_doc_attributes = true
reorder_impl_items = true
normalize_comments = true
imports_granularity = "Crate"
report_fixme = "Always"
error_on_unformatted = true
